spring:
  application:
    name: retail-management-system
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/retail_management_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
server:
  port: 8080
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false

jwt:
  private-key: |-
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCpq/2PjUFQRR1PNQSqg3/NUmHEnnT3PJkg3zEm2c0Lh5WGlNeqzYqCN7hYwAvY7y/FwNSjxolSjI7gj3F6+RVyeQRVinnL5shsPGhpQk0r15cGaDi28o1uiaHh06q7YwCk2f2yMq4xEYZSfzj7wq7aNYJRNc8qRCxwuPOqyjUaaV83JKHW6SofTTxzgLjInCGJF0mXtfTcZHsash0klTIx/839TpFpuymsSwnoUv2DcWzbsox56GIl7GHfuEFfUg2sYAUh5nf+EqzOEnuiR2pK3Dfysa5AcnS1Z9l/hUhKF7Yv+7lHIVfR9DC7dcnLT2XMQkYBZFPmXQYUHKpYtbrTAgMBAAECggEABMrJx5MqxBSfpkwODK7YHjl0b3Q2Q4FfpdEH91vxcaDrtThg+v8BKXpfZ4pNC1x+EezHVLTXzhAQPQFwKBP+6hPG7o+RrxOel4gBPu/TdCiLqG+rImepXPTgMJuk19QNAZrykmTiDJq9G3liZ6HxBFK8koSdjEkOpERlBW7enxdM/lcgSEDYH/eqPz5Fuva8nBwzz4RLG+TLZm1UbM8dHSRpHTC1PAUm5aB7qsVR5fDH/QYZg6PuRlaBHXWRvmTWURZ/piX3vm18I1zMbW36W1OkNNGvCKK3rrOz8rG8VMWeWiE0Wu2w3k3/2tDFYiBj2HPZJWxQXUUEWFxoRbWsuQKBgQDBzauyq84XW3ribsjbiHmLx2hzcHEjjo+r8EnUdEKAFKI7NXkbUlZOigJy712lXYjJPFw3kRMKT+/n18bMnnvsqsXmls/tWdy+CM64YBkqDg25DlwAZQGHrrPNn0AniNt3q2eKNM6pJjtT+0qUJmL/k3u6ExVai7JEuOpkLosZrQKBgQDgH71yXbUXWuDYBpUnWT3jx+6+Z21kbuYx4kAO29BspqDkS/A7w84d06yuT4nKNmlFdvC+DmPyJUPHWQhi6sznEUGAyad/qShwYdVJhRBEwmh9/5iACNbPyT5Clt/i3Ocrmug0ldflk/PB8gKFUj/M3WY0WOB/tF+SR948d5+2fwKBgFUQz5JnMtixwKhu9B7YMnGWH1S8QAzZYFqZ5+4m8aGCbQsMF5JUe6mRji2gvzv8aDPcGKYTOYZHPAhJf+sEjWR+OMtT2wRVczy+ZO4s0B7TeFaH5P4PV7KUjjts8R3pRluqkpHpR+Sa8WOVY1DP4JhJxf8QrUjHFIJxoABFJa0pAoGAD6cH0xHqUMw/AbdL+WiJIvxWlyOgBzCbkQZNFPyTDNOCTw9iornlDj43RCE37VBpf7lzzMIyhrnFhwmXxVjCoKya14S91vOYaGjcvXq2jSbKp2oPW3nCjtZuK7ZfwndNCcWSzAFfB6CSmIvvUyJQZF1eAu/mFeUh+5RbV/u+wr8CgYA8PtuLWtptv1ADrqi+pX6Cawa8NOUaGMB2TLoD5UW8xtAs5eZztDD6a9DDgYJvGQFFePeZQLcemJDxRyNocmBW0heXeEGOFkdYo0R2ZuP3sj/PsllcTUVguSpPjHvaz8IqtVTWvdADUw39Td8bjCekypeABYZB7ELF0205FubRbw==
  public-key: |-
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqav9j41BUEUdTzUEqoN/zVJhxJ509zyZIN8xJtnNC4eVhpTXqs2Kgje4WMAL2O8vxcDUo8aJUoyO4I9xevkVcnkEVYp5y+bIbDxoaUJNK9eXBmg4tvKNbomh4dOqu2MApNn9sjKuMRGGUn84+8Ku2jWCUTXPKkQscLjzqso1GmlfNySh1ukqH008c4C4yJwhiRdJl7X03GR7GrIdJJUyMf/N/U6RabsprEsJ6FL9g3Fs27KMeehiJexh37hBX1INrGAFIeZ3/hKszhJ7okdqStw38rGuQHJ0tWfZf4VIShe2L/u5RyFX0fQwu3XJy09lzEJGAWRT5l0GFByqWLW60wIDAQAB

