name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -p123456 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: retail_management_system
          MYSQL_USER: root
          MYSQL_PASSWORD: 123456

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 JDK 版本
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 验证 MySQL 服务是否可用
      - name: Wait for MySQL to initialize
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..10}; do
            if mysqladmin ping -h 127.0.0.1 -u root -p123456 --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done

      # 验证数据库连接
      - name: Verify database connection
        run: |
          mysql -h 127.0.0.1 -u root -p123456 -e "SHOW DATABASES;"

      # 缓存 Maven 依赖
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 构建项目
      - name: Build with Maven
        run: mvn clean install

      # 执行测试
      - name: Run tests
        run: mvn test
